### ISSUE TITLE
Testing InformixHQ - error message at server startup - Informix 12.10.FC9DE

### ISSUE THREAD

**Issue by MarinitesteMC** [informix/informixhq-server#1]
Hello, friends.

Just testing the new InformixHQ, and some strange things here (starting the server):
Logged as user informix, with the default ol_informix1210.ksh script set:

I noticed that the embedded java version of Informix server is 1.7. There was a message saying that it was not correct:
# START NON-TRANSLATABLEjava.lang.UnsupportedClassVersionError: JVMCFRE003 invalid main version; class=com/informix/hq/server/JettyServer, offset=6

So, after altering my PATH variable to my JRE 1.8, and starting it again, getting the following issues:

[main] INFO com.informix.hq.server.JettyServer - Reading properties file informixhq-server.properties
[main] ERROR com.informix.hq.server.h2.H2ServerConfig - Error saving server config to H2
org.h2.jdbc.JdbcSQLException: The database is read only; SQL statement:
update config set data = ? [90097-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Database.checkWritingAllowed(Database.java:1924)
	at org.h2.table.Table.checkWritingAllowed(Table.java:1159)
	at org.h2.engine.User.hasRight(User.java:114)
	at org.h2.engine.User.checkRight(User.java:100)
	at org.h2.command.dml.Update.update(Update.java:87)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146)
	at com.informix.hq.server.h2.H2ServerConfig.updateConfig(H2ServerConfig.java:118)
	at com.informix.hq.server.h2.H2ServerConfig.createDefaultConfigsIfNeeded(H2ServerConfig.java:100)
	at com.informix.hq.server.JettyServer.main(JettyServer.java:178)
[main] INFO com.informix.hq.server.alerting.AlertingIncident - Loaded 0 incidents from H2
[main] INFO com.informix.hq.server.JettyServer - Loading package: /package-example.json
[main] ERROR com.informix.hq.server.JettyServer - Unexpected exception in JettyServer
java.lang.RuntimeException: Could not update sensor type in database
	at com.informix.hq.server.h2.H2SensorTypeCache.update(H2SensorTypeCache.java:129)
	at com.informix.hq.server.h2.H2SensorTypeCache.update(H2SensorTypeCache.java:33)
	at com.informix.hq.server.AbstractObjectManager.update(AbstractObjectManager.java:86)
	at com.informix.hq.server.JettyServer.loadPackage(JettyServer.java:457)
	at com.informix.hq.server.JettyServer.loadPackages(JettyServer.java:410)
	at com.informix.hq.server.JettyServer.main(JettyServer.java:233)
Caused by: org.h2.jdbc.JdbcSQLException: The database is read only; SQL statement:
update sensor_types set name = ?, description = ?, meta = ? where id = ? [90097-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Database.checkWritingAllowed(Database.java:1924)
	at org.h2.table.Table.checkWritingAllowed(Table.java:1159)
	at org.h2.engine.User.hasRight(User.java:114)
	at org.h2.engine.User.checkRight(User.java:100)
	at org.h2.command.dml.Update.update(Update.java:87)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146)
	at com.informix.hq.server.h2.H2SensorTypeCache.update(H2SensorTypeCache.java:127)

As I am running it with informix, don't know what database is read only (sysadmin is ok, I can access it via dbaccess).

Is there some additional pre-req that was not mentioned on the documentation page?

Please advice.
Thanks a lot.

**Comment by lfsm** [comment]
H2 is the embedded java database that InformixHQ will use to save the settings (servers, passwords, sensors, etc). It should be a file created in the same directory of the InformixHQ jar (or maybe in the directory from where you launch InformixHQ).
Do you have write permissions on the directories that you are using?

**Comment by MarinitesteMC** [comment]
Hi, Luis. Yes, I copied the two jar files (server and client) to the
INFORMIXDIR, and I am trying to start the server with informix user.

Is there any other clue?
Thanks for the internal explanations.


Em sáb, 5 de mai de 2018 19:10, Luis Marques <notifications@github.com>
escreveu:

**Comment by lfsm** [comment]
On my testing, I usually do not place the InformixHQ jars in the INFORMIXDIR. I just create a new directory for then (outside the INFORMIXDIR).

So on my testing VM I have INFORMIXDIR as:

`/usr/informix/srvr1210fc10de`

Then I created the dir `/usr/informix/informixhq` where I have the following files:
```
h2db.mv.db
informixhq-agent-0.1.0.jar
informixhq-server-0.1.0.jar
informixhq-server.properties
run_informixhq.ksh
```
The `h2db.mv.db`  is the H2 database (created on the first run of the InformixHQ server jar). 
My `informixhq-server.properties`is the following (just for testing):
```
initialAdminPassword=myPassword
httpPort=9090
httpsPort=-1

```
And the shell scripts sets up the java 1.8 openjdk environment variables and runs the InformixHQ server jar (I am using centos 7, openjdk 1.8):
```
export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64
export JRE_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre
export PATH=$JAVA_HOME/bin:$JRE_HOME/bin:$PATH

java -jar informixhq-server-0.1.0.jar informixhq-server.properties
```

Maybe having the InformixHQ jars in INFORMIXDIR is problematic.

**Comment by ekuehnhausen** [comment]
Has this been resolved? Can we close out this issue?

**Comment by ekuehnhausen** [comment]
Closing this as answered. Please reopen this or open a new issue if you run into any more problems.
